import sys
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from model import (  # noqa: E402
    CpuReadPipeline, Descriptor, DownloadModel, INDEX_BASE, INDEX_CVSD,
    INDEX_DESCRIPTOR, INDEX_OPTIONS_PCB, INDEX_OPTIONS_SHIFT, INDEX_QUESTIONS,
    PROFILES, ProtocolError, delayed_cpu_read, encode_descriptor, question_store_offset,
)
from mra_order import inspect_many, inspect_mra  # noqa: E402


def send(model, index, data, addresses=None):
    model.begin_transfer(index)
    addresses = range(len(data)) if addresses is None else addresses
    for address, value in zip(addresses, data):
        model.write(address, value)
    model.end_transfer()


class ExtendedTransportTests(unittest.TestCase):
    def test_existing_six_mras_are_legacy_xml_order(self):
        rows = inspect_many(sorted(Path("releases").glob("*.mra")))
        self.assertEqual(len(rows), 6)
        self.assertTrue(all(row["transferOrder"] == [0, 1, 2, 3] for row in rows))
        self.assertEqual({row["romNodes"][1]["firstInlinePayloadHex"] for row in rows}, {"01", "02", "10", "30"})

    def test_synthetic_mra_order_is_explicit_and_reproducible(self):
        xml = b"""<misterromdescription><rom index="1"><part>B0</part></rom>
          <rom index="7"><part>45 58</part></rom><rom index="0"/>
          <rom index="5"/><rom index="2"><part>37</part></rom></misterromdescription>"""
        path = HERE / "_fixture_extended.mra"
        path.write_bytes(xml)
        try:
            row = inspect_mra(path)
            self.assertEqual(row["transferOrder"], [1, 7, 0, 5, 2])
            self.assertEqual(row["romNodes"][0]["firstInlinePayloadHex"], "b0")
        finally:
            path.unlink(missing_ok=True)

    def test_valid_mouse_trap_transfer_and_unrelated_index2(self):
        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, bytes((0x90,)))
        self.assertTrue(model.reset)
        send(model, INDEX_DESCRIPTOR, encode_descriptor(3, base_bytes=4))
        self.assertTrue(model.reset)
        send(model, INDEX_BASE, b"BASE")
        self.assertTrue(model.reset)
        voice = bytes((i & 0xff for i in range(0x4000)))
        send(model, INDEX_CVSD, voice)
        self.assertTrue(model.expansion_ready)
        self.assertFalse(model.extended_armed)  # marker disarmed after completion
        self.assertFalse(model.reset)
        self.assertEqual(model.storage[INDEX_CVSD], voice)
        send(model, INDEX_OPTIONS_SHIFT, b"7")
        self.assertTrue(model.expansion_ready)  # trailing settings don't invalidate data
        self.assertFalse(model.reset)

    def test_descriptor_bytes_match_published_masks_and_lengths(self):
        # Fixed bytes are transcribed from the accepted descriptor layout, not
        # generated by encode_descriptor, so shared encoder/parser bugs are caught.
        mouse = bytes.fromhex("45 58 01 03 05 01 00 00 00 00 00 00 40 00 00 00")
        parsed = Descriptor.parse(mouse)
        self.assertEqual(parsed.required_mask, 0x05)  # stream slots 0 and 2: indexes 0 and 6
        self.assertEqual(parsed.lengths, {0: 1, 5: 0, 6: 0x4000})
        self.assertEqual(encode_descriptor(3, 1), mouse)

        fax = bytes.fromhex("45 58 01 01 03 00 00 01 00 00 03 00 00 00 00 00")
        self.assertEqual(Descriptor.parse(fax).required_mask, 0x03)
        self.assertEqual(Descriptor.parse(fax).lengths, {0: 0x10000, 5: 0x30000, 6: 0})

    def test_fax_and_fax2_descriptor_distinguish_same_pcb_flags(self):
        for profile in (1, 2):
            descriptor = Descriptor.parse(encode_descriptor(profile, 0x10000))
            self.assertEqual(descriptor.profile_id, profile)
            self.assertEqual(PROFILES[profile][1], 0x30)
            self.assertEqual(descriptor.lengths[INDEX_QUESTIONS], 24 * 0x2000)
            self.assertEqual(descriptor.lengths[INDEX_CVSD], 0)

    def test_valid_fax_and_fax2_streams_fill_exact_question_capacity(self):
        questions = bytes(range(256)) * (24 * 0x2000 // 256)
        for profile in (1, 2):
            model = DownloadModel()
            send(model, INDEX_OPTIONS_PCB, b"\xb0")
            send(model, INDEX_DESCRIPTOR, encode_descriptor(profile, 3))
            send(model, INDEX_BASE, b"ROM")
            send(model, INDEX_QUESTIONS, questions)
            self.assertTrue(model.expansion_ready)
            self.assertFalse(model.reset)
            self.assertEqual(len(model.storage[INDEX_QUESTIONS]), 0x30000)

    def test_marker_descriptor_and_base_fail_closed(self):
        # Truncated marker transfer leaves reset asserted and cannot reuse old data.
        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90\x00")
        self.assertTrue(model.reset)
        self.assertFalse(model.expansion_ready)
        self.assertIsNotNone(model.invalid_reason)

        aborted = DownloadModel()
        send(aborted, INDEX_OPTIONS_PCB, b"")
        self.assertTrue(aborted.reset)  # marker transfer aborted before byte zero
        self.assertFalse(aborted.expansion_ready)

        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        malformed = bytearray(encode_descriptor(3, 4))
        malformed[4] ^= 0x01  # wrong stream mask
        send(model, INDEX_DESCRIPTOR, bytes(malformed))
        self.assertTrue(model.reset)
        self.assertFalse(model.expansion_ready)

        for field in (2, 3, 14):  # version, unknown profile, reserved bytes
            malformed = bytearray(encode_descriptor(3, 4))
            malformed[field] = 0xff
            candidate = DownloadModel()
            send(candidate, INDEX_OPTIONS_PCB, b"\x90")
            send(candidate, INDEX_DESCRIPTOR, bytes(malformed))
            self.assertTrue(candidate.reset)
            self.assertFalse(candidate.expansion_ready)

        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        send(model, INDEX_DESCRIPTOR, encode_descriptor(3, 5))
        send(model, INDEX_BASE, b"BASE")
        self.assertTrue(model.reset)  # descriptor present, incomplete base stream
        self.assertFalse(model.expansion_ready)

    def test_duplicate_holes_extra_and_wrong_order_fail_closed(self):
        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        # Payload arriving before descriptor is invalid.
        send(model, INDEX_BASE, b"x")
        self.assertTrue(model.reset)
        self.assertIsNotNone(model.invalid_reason)

        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        send(model, INDEX_DESCRIPTOR, encode_descriptor(3, 1))
        send(model, INDEX_CVSD, bytes(0x4000))  # CVSD cannot precede declared base index 0
        self.assertTrue(model.reset)
        self.assertIsNotNone(model.invalid_reason)
        send(model, INDEX_OPTIONS_SHIFT, b"7")
        self.assertTrue(model.reset)  # unrelated option cannot clear fault hold

        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        send(model, INDEX_DESCRIPTOR, encode_descriptor(3, 2))
        send(model, INDEX_BASE, b"AB", addresses=(0, 2))
        self.assertTrue(model.reset)
        self.assertFalse(model.expansion_ready)

    def test_extended_to_legacy_index0_then1_clears_stale_data(self):
        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        send(model, INDEX_DESCRIPTOR, encode_descriptor(3, 1))
        send(model, INDEX_BASE, b"B")
        send(model, INDEX_CVSD, bytes(0x4000))
        self.assertTrue(model.expansion_ready)
        self.assertEqual(len(model.storage[INDEX_CVSD]), 0x4000)
        # Existing loader sends index 0 before index 1 in every legacy MRA.
        send(model, INDEX_BASE, b"L" * 12)
        self.assertFalse(model.expansion_ready)
        self.assertNotIn(INDEX_CVSD, model.storage)
        self.assertFalse(model.reset)
        send(model, INDEX_OPTIONS_PCB, b"\x10")
        self.assertFalse(model.expansion_ready)
        self.assertFalse(model.reset)

    def test_fresh_marker_clears_extension_but_preserves_base_memory(self):
        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        send(model, INDEX_DESCRIPTOR, encode_descriptor(3, 1))
        send(model, INDEX_BASE, b"B")
        send(model, INDEX_CVSD, bytes(0x4000))
        self.assertTrue(model.expansion_ready)
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        self.assertTrue(model.reset)
        self.assertFalse(model.expansion_ready)
        self.assertNotIn(INDEX_CVSD, model.storage)
        self.assertEqual(model.base_memory[0], ord("B"))

    def test_invalid_profile_pcb_and_duplicate_stream_hold_reset(self):
        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\xb0")  # wrong low bits for CVSD profile
        send(model, INDEX_DESCRIPTOR, encode_descriptor(3, 1))
        self.assertTrue(model.reset)
        self.assertIn("PCB", model.invalid_reason)

        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        send(model, INDEX_DESCRIPTOR, encode_descriptor(3, 1))
        send(model, INDEX_BASE, b"B")
        send(model, INDEX_CVSD, bytes(0x4000))
        self.assertTrue(model.expansion_ready)
        send(model, INDEX_CVSD, bytes(0x4000))
        self.assertTrue(model.reset)
        self.assertFalse(model.expansion_ready)

    def test_faulted_expansion_config_fault_revokes_ready_until_new_generation(self):
        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        send(model, INDEX_DESCRIPTOR, encode_descriptor(3, 1))
        send(model, INDEX_BASE, b"B")
        send(model, INDEX_CVSD, bytes(0x4000))
        self.assertTrue(model.expansion_ready)
        # Even an unrelated config transfer with malformed address progression
        # invalidates readiness and holds reset; it cannot preserve stale reads.
        model.begin_transfer(INDEX_OPTIONS_SHIFT)
        model.write(0, ord("7"))
        model.write(2, ord("8"))
        model.end_transfer()
        self.assertTrue(model.reset)
        self.assertFalse(model.expansion_ready)
        self.assertNotIn(INDEX_CVSD, model.storage)

    def test_faulted_extended_session_recovers_on_legacy0_then1_without_losing_base_writes(self):
        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        send(model, INDEX_DESCRIPTOR, encode_descriptor(3, 2))
        send(model, INDEX_BASE, b"X")  # truncated extended base
        self.assertTrue(model.reset)
        # Existing legacy order starts a fresh index-0 write before index 1.
        send(model, INDEX_BASE, b"LEGACY")
        self.assertTrue(model.reset)  # ambiguous old descriptor remains fail-closed
        self.assertEqual(bytes(model.base_memory[i] for i in range(6)), b"LEGACY")
        send(model, INDEX_OPTIONS_PCB, b"\x10")
        self.assertFalse(model.reset)
        self.assertFalse(model.expansion_ready)
        self.assertEqual(bytes(model.base_memory[i] for i in range(6)), b"LEGACY")

    def test_short_long_and_duplicate_byte_counts_fault_until_fresh_session(self):
        for payload in (b"", b"AB"):
            model = DownloadModel()
            send(model, INDEX_OPTIONS_PCB, b"\x90")
            send(model, INDEX_DESCRIPTOR, encode_descriptor(3, 1))
            send(model, INDEX_BASE, payload)  # expected one byte
            self.assertTrue(model.reset)
            self.assertFalse(model.expansion_ready)
            send(model, INDEX_OPTIONS_SHIFT, b"7")
            self.assertTrue(model.reset)  # config cannot release a faulted session

        model = DownloadModel()
        send(model, INDEX_OPTIONS_PCB, b"\x90")
        send(model, INDEX_DESCRIPTOR, encode_descriptor(3, 2))
        send(model, INDEX_BASE, b"AB")
        send(model, INDEX_BASE, b"CD")  # duplicate base before CVSD is rejected
        self.assertTrue(model.reset)
        self.assertFalse(model.expansion_ready)


class CpuMemoryTimingTests(unittest.TestCase):
    def test_question_address_boundaries_and_unpopulated_fallback(self):
        self.assertEqual(question_store_offset(0, 0x2000), 0)
        self.assertEqual(question_store_offset(0, 0x3fff), 0x1fff)
        self.assertEqual(question_store_offset(23, 0x3fff), 24 * 0x2000 - 1)
        self.assertIsNone(question_store_offset(24, 0x2000))
        for address in (0x1fff, 0x4000):
            with self.assertRaises(ValueError):
                question_store_offset(0, address)

    def test_registered_bram_plus_cpu_data_pipeline_meets_64_clock_enable(self):
        # Each physical bank gets a unique pattern; edge data checks both bank and offset.
        memory = {0: 0xA0, 0x1fff: 0xAF, 0x2000: 0xB0, 24 * 0x2000 - 1: 0xC7}
        pipe = CpuReadPipeline(memory)
        for _ in range(4):
            pipe.tick(0)
        # Address changes at one CPU enable. First two edge samples see old
        # registered input; the third edge can sample the new value.
        self.assertEqual(pipe.tick(0x2000), 0xA0)
        self.assertEqual(pipe.tick(0x2000), 0xA0)
        self.assertEqual(pipe.tick(0x2000), 0xB0)
        self.assertEqual(delayed_cpu_read(pipe, 0x1fff, 64), 0xAF)
        self.assertEqual(delayed_cpu_read(pipe, 24 * 0x2000 - 1, 64), 0xC7)
        self.assertEqual(delayed_cpu_read(pipe, 0x777777, 64), 0)
        with self.assertRaises(ValueError):
            delayed_cpu_read(pipe, 0, 1)

        # Adversarial timing: if a selector/address changes only on the sampling
        # edge, registered CPU data is stale. The wait-state/prefetch contract
        # must prevent this case if the actual circuit can produce it.
        late = CpuReadPipeline(memory)
        for _ in range(4):
            late.tick(0)
        for _ in range(63):
            late.tick(0)
        stale = late.tick(0x2000)
        self.assertEqual(stale, 0xA0)
        self.assertNotEqual(stale, memory[0x2000])


if __name__ == "__main__":
    unittest.main()
